// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: mcp.proto

package mcpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType distinguishes between requests, responses, and notifications.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// REQUEST indicates a message expecting a response.
	MessageType_MESSAGE_TYPE_REQUEST MessageType = 1
	// RESPONSE indicates a reply to a previous request.
	MessageType_MESSAGE_TYPE_RESPONSE MessageType = 2
	// NOTIFICATION indicates a one-way message (no response expected).
	MessageType_MESSAGE_TYPE_NOTIFICATION MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_REQUEST",
		2: "MESSAGE_TYPE_RESPONSE",
		3: "MESSAGE_TYPE_NOTIFICATION",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_REQUEST":      1,
		"MESSAGE_TYPE_RESPONSE":     2,
		"MESSAGE_TYPE_NOTIFICATION": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_mcp_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

// Message is the envelope for all MCP communication over gRPC.
// It uses a hybrid approach: strongly-typed envelope fields with
// JSON-encoded payloads for method-specific params and results.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type indicates whether this is a request, response, or notification.
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=mcp.v1.MessageType" json:"type,omitempty"`
	// Request fields (used when type == MESSAGE_TYPE_REQUEST)
	// request_id uniquely identifies the request for correlation with response.
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// method is the MCP method name (e.g., "tools/call", "resources/read").
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// params contains JSON-encoded method parameters.
	Params []byte `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	// meta contains request metadata like progress tokens.
	Meta *RequestMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	// Response fields (used when type == MESSAGE_TYPE_RESPONSE)
	// result contains JSON-encoded successful response data.
	Result []byte `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	// error contains error details if the request failed.
	Error *Error `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// Common metadata for headers, tracing IDs, auth tokens, etc.
	// This maps naturally to gRPC metadata and HTTP headers.
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Message) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Message) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Message) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Message) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RequestMeta contains metadata attached to requests.
type RequestMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// progress_token enables progress reporting for long-running operations.
	// When present, the server may send progress notifications.
	ProgressToken string `protobuf:"bytes,1,opt,name=progress_token,json=progressToken,proto3" json:"progress_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	mi := &file_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMeta) GetProgressToken() string {
	if x != nil {
		return x.ProgressToken
	}
	return ""
}

// Error represents an MCP/JSON-RPC error.
// Error codes follow JSON-RPC 2.0 conventions:
//
//	-32700: Parse error
//	-32600: Invalid request
//	-32601: Method not found
//	-32602: Invalid params
//	-32603: Internal error
//	-32001: Not found (MCP extension)
//	-32002: Unauthorized (MCP extension)
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the JSON-RPC error code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// message is a human-readable error description.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// data contains optional JSON-encoded additional error details.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ProgressParams contains parameters for progress notifications.
// Sent via notifications/progress method.
type ProgressParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// progress_token correlates with the original request.
	ProgressToken string `protobuf:"bytes,1,opt,name=progress_token,json=progressToken,proto3" json:"progress_token,omitempty"`
	// progress is the current progress value.
	Progress float64 `protobuf:"fixed64,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// total is the optional maximum progress value.
	Total *float64 `protobuf:"fixed64,3,opt,name=total,proto3,oneof" json:"total,omitempty"`
	// message is an optional human-readable progress description.
	Message       *string `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressParams) Reset() {
	*x = ProgressParams{}
	mi := &file_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressParams) ProtoMessage() {}

func (x *ProgressParams) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressParams.ProtoReflect.Descriptor instead.
func (*ProgressParams) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *ProgressParams) GetProgressToken() string {
	if x != nil {
		return x.ProgressToken
	}
	return ""
}

func (x *ProgressParams) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressParams) GetTotal() float64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *ProgressParams) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// LogMessageParams contains parameters for log message notifications.
// Sent via notifications/message method.
type LogMessageParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// level is the log level (debug, info, notice, warning, error, critical, alert, emergency).
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	// logger identifies the source of the log message.
	Logger string `protobuf:"bytes,2,opt,name=logger,proto3" json:"logger,omitempty"`
	// data contains JSON-encoded log data.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessageParams) Reset() {
	*x = LogMessageParams{}
	mi := &file_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessageParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessageParams) ProtoMessage() {}

func (x *LogMessageParams) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessageParams.ProtoReflect.Descriptor instead.
func (*LogMessageParams) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *LogMessageParams) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogMessageParams) GetLogger() string {
	if x != nil {
		return x.Logger
	}
	return ""
}

func (x *LogMessageParams) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ResourceUpdatedParams contains parameters for resource update notifications.
// Sent via notifications/resources/updated method.
type ResourceUpdatedParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uri identifies the resource that was updated.
	Uri           string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUpdatedParams) Reset() {
	*x = ResourceUpdatedParams{}
	mi := &file_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUpdatedParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUpdatedParams) ProtoMessage() {}

func (x *ResourceUpdatedParams) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUpdatedParams.ProtoReflect.Descriptor instead.
func (*ResourceUpdatedParams) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceUpdatedParams) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// CancelledParams contains parameters for cancellation notifications.
// Sent via notifications/cancelled method.
type CancelledParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id identifies the cancelled request.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// reason optionally explains why the request was cancelled.
	Reason        *string `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelledParams) Reset() {
	*x = CancelledParams{}
	mi := &file_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelledParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelledParams) ProtoMessage() {}

func (x *CancelledParams) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelledParams.ProtoReflect.Descriptor instead.
func (*CancelledParams) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *CancelledParams) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelledParams) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_mcp_proto protoreflect.FileDescriptor

const file_mcp_proto_rawDesc = "" +
	"\n" +
	"\tmcp.proto\x12\x06mcp.v1\"\xdf\x02\n" +
	"\aMessage\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.mcp.v1.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x04 \x01(\fR\x06params\x12'\n" +
	"\x04meta\x18\x05 \x01(\v2\x13.mcp.v1.RequestMetaR\x04meta\x12\x16\n" +
	"\x06result\x18\x06 \x01(\fR\x06result\x12#\n" +
	"\x05error\x18\a \x01(\v2\r.mcp.v1.ErrorR\x05error\x129\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1d.mcp.v1.Message.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\vRequestMeta\x12%\n" +
	"\x0eprogress_token\x18\x01 \x01(\tR\rprogressToken\"I\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xa3\x01\n" +
	"\x0eProgressParams\x12%\n" +
	"\x0eprogress_token\x18\x01 \x01(\tR\rprogressToken\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x01R\bprogress\x12\x19\n" +
	"\x05total\x18\x03 \x01(\x01H\x00R\x05total\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x01R\amessage\x88\x01\x01B\b\n" +
	"\x06_totalB\n" +
	"\n" +
	"\b_message\"T\n" +
	"\x10LogMessageParams\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06logger\x18\x02 \x01(\tR\x06logger\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\")\n" +
	"\x15ResourceUpdatedParams\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"X\n" +
	"\x0fCancelledParams\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason*\x7f\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MESSAGE_TYPE_REQUEST\x10\x01\x12\x19\n" +
	"\x15MESSAGE_TYPE_RESPONSE\x10\x02\x12\x1d\n" +
	"\x19MESSAGE_TYPE_NOTIFICATION\x10\x0326\n" +
	"\x03MCP\x12/\n" +
	"\aConnect\x12\x0f.mcp.v1.Message\x1a\x0f.mcp.v1.Message(\x010\x01B3Z1github.com/anthropics/mcp-go/transport/grpc/mcpv1b\x06proto3"

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData []byte
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)))
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mcp_proto_goTypes = []any{
	(MessageType)(0),              // 0: mcp.v1.MessageType
	(*Message)(nil),               // 1: mcp.v1.Message
	(*RequestMeta)(nil),           // 2: mcp.v1.RequestMeta
	(*Error)(nil),                 // 3: mcp.v1.Error
	(*ProgressParams)(nil),        // 4: mcp.v1.ProgressParams
	(*LogMessageParams)(nil),      // 5: mcp.v1.LogMessageParams
	(*ResourceUpdatedParams)(nil), // 6: mcp.v1.ResourceUpdatedParams
	(*CancelledParams)(nil),       // 7: mcp.v1.CancelledParams
	nil,                           // 8: mcp.v1.Message.MetadataEntry
}
var file_mcp_proto_depIdxs = []int32{
	0, // 0: mcp.v1.Message.type:type_name -> mcp.v1.MessageType
	2, // 1: mcp.v1.Message.meta:type_name -> mcp.v1.RequestMeta
	3, // 2: mcp.v1.Message.error:type_name -> mcp.v1.Error
	8, // 3: mcp.v1.Message.metadata:type_name -> mcp.v1.Message.MetadataEntry
	1, // 4: mcp.v1.MCP.Connect:input_type -> mcp.v1.Message
	1, // 5: mcp.v1.MCP.Connect:output_type -> mcp.v1.Message
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	file_mcp_proto_msgTypes[3].OneofWrappers = []any{}
	file_mcp_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		EnumInfos:         file_mcp_proto_enumTypes,
		MessageInfos:      file_mcp_proto_msgTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
