// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: mcp.proto

package mcpv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCP_Connect_FullMethodName = "/mcp.v1.MCP/Connect"
)

// MCPClient is the client API for MCP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MCP service provides bidirectional Model Context Protocol communication.
// This service enables agents and tools to communicate using gRPC as the
// transport layer while maintaining full MCP protocol compatibility.
type MCPClient interface {
	// Connect establishes a bidirectional stream for MCP communication.
	// Both client and server can send messages at any time, enabling:
	// - Client requests (tools/call, resources/read, etc.)
	// - Server responses
	// - Server-to-client requests (sampling/createMessage, roots/list)
	// - Notifications in both directions (progress, resource updates, etc.)
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type mCPClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPClient(cc grpc.ClientConnInterface) MCPClient {
	return &mCPClient{cc}
}

func (c *mCPClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MCP_ServiceDesc.Streams[0], MCP_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCP_ConnectClient = grpc.BidiStreamingClient[Message, Message]

// MCPServer is the server API for MCP service.
// All implementations must embed UnimplementedMCPServer
// for forward compatibility.
//
// MCP service provides bidirectional Model Context Protocol communication.
// This service enables agents and tools to communicate using gRPC as the
// transport layer while maintaining full MCP protocol compatibility.
type MCPServer interface {
	// Connect establishes a bidirectional stream for MCP communication.
	// Both client and server can send messages at any time, enabling:
	// - Client requests (tools/call, resources/read, etc.)
	// - Server responses
	// - Server-to-client requests (sampling/createMessage, roots/list)
	// - Notifications in both directions (progress, resource updates, etc.)
	Connect(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedMCPServer()
}

// UnimplementedMCPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPServer struct{}

func (UnimplementedMCPServer) Connect(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMCPServer) mustEmbedUnimplementedMCPServer() {}
func (UnimplementedMCPServer) testEmbeddedByValue()             {}

// UnsafeMCPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPServer will
// result in compilation errors.
type UnsafeMCPServer interface {
	mustEmbedUnimplementedMCPServer()
}

func RegisterMCPServer(s grpc.ServiceRegistrar, srv MCPServer) {
	// If the following call panics, it indicates UnimplementedMCPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCP_ServiceDesc, srv)
}

func _MCP_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MCPServer).Connect(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCP_ConnectServer = grpc.BidiStreamingServer[Message, Message]

// MCP_ServiceDesc is the grpc.ServiceDesc for MCP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.v1.MCP",
	HandlerType: (*MCPServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _MCP_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mcp.proto",
}
